### ISSUE TITLE
Request to move an entry from the 'Plugins' section to the 'Integrations' section

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#15]
Hello, would it be possible to move the 'Atlas Systems: Aeon/ArchivesSpace Plugins' entry from the 'Additional Back-end Functionality' category in the 'Plugins' section to the 'Import/Export' category of the 'Integrations' section? The Atlas Systems plugin and addon support the integration between ArchivesSpace and Aeon. Thanks.

**Comment by mjhugh** [comment]
Done -- Moved the Aeon/ASpace plugins entry to Integrations: Import/Export. Thank you!
