### ISSUE TITLE
New Resource for the APIs and Scripts section

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#22]
<a href="https://saaers.wordpress.com/2018/10/30/using-python-ffmpeg-and-the-archivesspace-api-to-create-a-lightweight-clip-library/">Using Python, FFMPEG, and the ArchivesSpace API to Create a Lightweight Clip Library</a> (Bonnie Gordon, Rockefeller Archive Center): Explains how the Center created a Python script that "uses the ArchivesSpace API to gather descriptive metadata and output it to a spreadsheet, and also uses the command line tool ffmpeg to automate [audio/visual] clip creation."

**Comment by mjhugh** [comment]
Thanks for sending this, Anne Marie! I'll add it now.
