### ISSUE TITLE
New Resource Addition

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#23]
This resource might be appropriate for the Migrations section, under the 'EAD or Homegrown database' subheading.

<a href="http://steady2.herokuapp.com/">Steady converts CSV into EAD XML</a> (Jason Ronallo, NCSU Libraries): This tool converts CSV resource records into EAD XML.

**Comment by mjhugh** [comment]
Good addition! Thank you. Adding now!
