### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#25]
Hello,

1. There is a typo under 'APIs and Scripts' in the 'ArchivesSpace Export Service' entry - the 'p' is missing from 'provides': https://www.screencast.com/t/tQ8xzZphmZXP 

2. There is a typo above the 'Plug-ins' section in the 'How I learned to stop worrying and love the API' entry - the first 'S' should be lowercase in 'ArchiveSSpace': https://www.screencast.com/t/S6e2304r62c

**Comment by mjhugh** [comment]
Hi Anne Marie - Thanks so much for sending this in! I'm fixing it now.
