### ISSUE TITLE
Sample AS implementation (branding and configuration)

### ISSUE THREAD

**Issue by terrywbrady** [archivesspace/awesome-archivesspace#27]
We have published a repo with our branding and configuration customizations for ArchivesSpace.

https://github.com/Georgetown-University-Libraries/GUArchivesspace

Would this be a useful resource to add to the awesome list?  If so, where should I link it?

**Comment by terrywbrady** [comment]
@mjhugh , that sounds like a good place to me.  Let me know if there is any additional information that I can provide.

**Comment by mjhugh** [comment]
@terrywbrady , Great. I've gone ahead and added the link to the Implementation section. Let me know if you want any other edits!
