### ISSUE TITLE
New Resource Addition for APIs and Scripts

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#34]
This blog post: https://saaers.wordpress.com/2019/04/09/using-r-to-migrate-box-and-folder-lists-into-ead/ describes how the author, Andy Meyer, used the programming language R to extract box and folder data from Microsoft Word documents to put into EADs that are then imported into ArchivesSpace.

**Comment by mjhugh** [comment]
I've added it to the list. Thanks, @amlyons !
