### ISSUE TITLE
Request to add new Script resource

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#36]
This resource: https://www2.archivists.org/groups/research-libraries-section/step-by-step-instructions-for-batch-editing-barcodes-in-archivessp is applicable to the API and Scripts section. 

"Step By Step Instructions for Batch Editing Barcodes in ArchivesSpace" by Vakil Smallen, International Brotherhood of Teamsters Labor History Archivist, George Washington University

**Comment by mjhugh** [comment]
Added it. Thanks, @amlyons !
