### ISSUE TITLE
New addition for the Plugins section

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#41]
New entry for the Plugins - "Additional Front-end Functionality"

* [Creating a static page for the PUI](https://github.com/hudmol/static_pages) (James Bullen, Hudson Molonglo): Can be used to create a static page for the PUI, such as an FAQ, instructions for searching, information about the archive, etc.    

Also, there's a typo in the entry from Tim DeLauro in the same section.

**Comment by mjhugh** [comment]
Added the link and fixed that typo. Thanks, @amlyons !
