### ISSUE TITLE
New addition for the Migrations section

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#42]
[Columbia University Libraries Migration to ArchivesSpace](https://journal.code4lib.org/articles/14871) (David W. Hodges and Kevin Schlottmann, CUL): Article describing a data migration from several sources - EADs, MARC records, Archivists Toolkit - to ArchivesSpace using Python scripts and API processes.

**Comment by mjhugh** [comment]
Got it. Thanks again!
