### ISSUE TITLE
Update broken link

### ISSUE THREAD

**Issue by amlyons** [archivesspace/awesome-archivesspace#45]
**Current text** (link is broken): List of links to a variety of ArchivesSpace training manuals (Hosted by SAA's Collection Management Tools Section) 

**New text** with updated link and section name: [List of links to a variety of ArchivesSpace training manuals](https://www2.archivists.org/groups/collection-management-section/cmt-documentation-portal) (Hosted by SAA's Collection Management Section)

**Comment by mjhugh** [comment]
Got it, @amlyons . Thank you!!
