### ISSUE TITLE
Question regarding ability to link OBO Foundry ontologies into ArchivesSpace

### ISSUE THREAD

**Issue by Superraptor** [archivesspace/awesome-archivesspace#51]
Hi! My name is Clair Kronk, I've created the GSSO (Gender, Sex, and Sexual Orientation) ontology, a controlled vocabulary of over 10,000 terms available here: http://www.ontobee.org/ontology/GSSO (and here: https://github.com/Superraptor/GSSO). I've had some interest from organizations wanting to link this vocabulary (and other OBO Foundry ontologies at Ontobee) into their ArchivesSpace records as tags.

Is there a plugin that would support this operation? There are RDF/XML, OWL, and JSON-LD versions of the GSSO, as well as a SPARQL API at Ontobee for access (http://www.ontobee.org/sparql) if that helps! Thanks so much for your time!

**Comment by searcy** [comment]
First, let me say "Hello!" And apologies for letting this issue languish here for so long. This is such an interesting idea!

As far as I know, there is not a plugin that would support this functionality, although I'm curious if perhaps it might be possible for someone keen to adapt the existing code for a plugin that already exists for importing agent or subject headings from the Library of Congress that is currently part of the core code -- I'm including a link to the relevant part of the code here: https://github.com/archivesspace/archivesspace/tree/master/plugins/lcnaf.

If you're looking to find a potential partner in this effort, I might suggest reaching out to the ArchivesSpace Google Group (https://groups.google.com/g/archivesspace), which is open to anyone or the User Group email list (http://lyralists.lyrasis.org/mailman/listinfo/archivesspace_users_group), which is restricted to ArchivesSpace members.

It sounds really interesting, and I think a number of folks would love to hear more if that's something that is pursued.
